+++
date = "2015-12-02T07:22:17+09:00"
title = "elixir学習日誌: 標準入出力..例外処理"
description = "elixir学習日誌: 標準入出力..例外処理"
tags = ["Elixir"]

+++

## 標準入出力

```elixir
IO.puts :stdio, "fantastic!"
IO.puts :stderr, "goddness!"
```

## 標準入力

```elixir
case IO.gets "What's your name?: " do
  "Tom\n"    -> IO.puts "Oh! Tom. Good name."
  "Jesica\n" -> IO.puts "Jesica! How are you?"
  _          -> IO.puts "Nobody knows you"
end
```

## ファイル操作

```elixir
File.write! "fruits.txt", "apple\norange\nbanana\n"
list = File.read! "fruits.txt"
IO.puts list
```

## Path操作

```elixir
Path.join "foo", "bar" # => foo/bar
Path.expand "~/baz"    # => /home/Users/baz
```

標準入出力・ファイル・PathはすべてRubyっぽい。

## 例外処理

どんな言語でもお馴染みの例外処理です。

```elixir
try do
  raise "Oh! My goddness."
rescue
  e in RuntimeError -> IO.inspect e
after
  IO.puts "What's up?"
end
```

Ruby訳すると分かりやすい。

```ruby
begin
  raise "Oh! My goddness."
rescue => e
  puts e.inspect
ensure
  puts "What's up?"
end
```

また、`try...catch`の使い方もある。

```elixir
try do
  throw "hello"
catch
  t -> IO.inspect t
end
```

再びRuby訳。これは少しニュアンスが変わりそうだけど、シグナルを受け取って、処理を抜ける意味では同じかな。

```ruby
catch :hello do
  3.times do |i|
    throw :hello if i == 2
  end
end
```

## 参考

* [Part16:入出力 | μ'sと学ぶソフトウェア開発入門](http://learn-with-muse.sato-t.net/?page_id=3821)
* [Part17:例外処理 | μ'sと学ぶソフトウェア開発入門](http://learn-with-muse.sato-t.net/?page_id=4061)

